spring:
  application:
    name: baluwo-challenge

api:
  endpoints:
    customer:
      name: customer
      mapping: /api/v1/customer
    product:
      name: product
      mapping: /api/v1/product
    buy:
      name: buy
      mapping: /api/v1/buy