spring:
  profiles: local
  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
    #show-sql: true
  datasource:
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost/baluwo_challenge
    #username: postgres
    #password: postgres
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa